"""Level Identity test.

For nested A, interval I=[b0,a0], T=[b0,a0+1]:
  P_M(delta) = prod_{(a,b) in M} (delta_b - delta_{a+1})   (delta_k, k in T)
  Competitors: nested B != A, weight N, phi(B) ⊵ phi(A), with n_I(B) = n_I(A).
Test whether P_{A_I} lies in the cone generated by {P_{B_I}} (LP on monomial coefficient vectors).
If NOT, A is extreme (by the level identity theorem).
"""
import sys, itertools, time
from collections import defaultdict
import numpy as np
from scipy.optimize import linprog
from schurcone import *
from epsjet import inside_pairs


def poly_of(M, T):
    """monomial-coefficient dict of prod (delta_b - delta_{a+1}); monomials as sorted tuples of variables."""
    poly = {(): 1}
    for (a, b) in M:
        new = defaultdict(int)
        for mono, c in poly.items():
            new[tuple(sorted(mono + (b,)))] += c
            new[tuple(sorted(mono + (a + 1,)))] -= c
        poly = {m: c for m, c in new.items() if c != 0}
    return poly


def level_test(A, b0, a0, comps=None, verbose=False):
    A = canon(A); lam = phi(A); N = sum(lam)
    if comps is None:
        comps = [B for B in nested_multisets(N) if B != A and dominates(phi(B), lam)]
    T = list(range(b0, a0 + 2))
    AI = tuple(sorted(inside_pairs(A, b0, a0), reverse=True)); n = len(AI)
    Ms = set()
    for B in comps:
        BI = inside_pairs(B, b0, a0)
        if len(BI) == n:
            Ms.add(tuple(sorted(BI, reverse=True)))
    if AI in Ms:
        return False, "some competitor has B_I = A_I", Ms
    PA = poly_of(AI, T)
    PMs = {M: poly_of(M, T) for M in Ms}
    monos = sorted(set(PA) | set(m for p in PMs.values() for m in p))
    idx = {m: i for i, m in enumerate(monos)}
    if not Ms:
        return True, "no competitors at level", Ms
    Mlist = list(Ms)
    Amat = np.zeros((len(monos), len(Mlist)))
    for j, M in enumerate(Mlist):
        for m, c in PMs[M].items():
            Amat[idx[m], j] = c
    bvec = np.zeros(len(monos))
    for m, c in PA.items():
        bvec[idx[m]] = c
    res = linprog(c=np.zeros(len(Mlist)), A_eq=Amat, b_eq=bvec, bounds=[(0, None)] * len(Mlist), method="highs")
    in_cone = (res.status == 0)
    return (not in_cone), ("in cone" if in_cone else "NOT in cone -> extreme"), Ms


if __name__ == "__main__":
    if sys.argv[1].startswith("N="):
        Nmax = int(sys.argv[1][2:])
        for N in range(4, Nmax + 1):
            gens = nested_multisets(N)
            t = time.time(); unproved = []
            for A in gens:
                if len(A) < 2: continue
                lam = phi(A)
                comps = [B for B in gens if B != A and dominates(phi(B), lam)]
                vals = sorted(set(lam))
                ok = False
                for b0 in vals:
                    for a0 in vals:
                        if a0 < b0: continue
                        good, why, Ms = level_test(A, b0, a0, comps)
                        if good:
                            ok = (b0, a0); break
                    if ok: break
                if not ok: unproved.append(A)
            print(f"N={N}: {len(gens)} nested, {len(unproved)} not proved by level identity [{time.time()-t:.0f}s]", flush=True)
            for A in unproved: print("      ", A)
    else:
        A = canon(eval(sys.argv[1])); lam = phi(A)
        b0 = int(sys.argv[2]); a0 = int(sys.argv[3])
        good, why, Ms = level_test(A, b0, a0, verbose=True)
        print(A, f"I=[{b0},{a0}]:", why)
        print("  level multisets M:", sorted(Ms))
